export const Icons = {
  User: () => <span className="text-lg">👤</span>,
  Home: () => <span className="text-lg">🏠</span>,
  Calculator: () => <span className="text-lg">🧮</span>,
  Robot: () => <span className="text-lg">🤖</span>,
  ChartLine: () => <span className="text-lg">📈</span>,
  Newspaper: () => <span className="text-lg">📰</span>,
  PaperPlane: () => <span className="text-lg">✈️</span>,
  Search: () => <span className="text-lg">🔍</span>,
  Spinner: () => <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-current"></div>,
  Upload: () => <span className="text-lg">📤</span>,
  CheckCircle: () => <span className="text-lg text-green-600">✅</span>,
  Brain: () => <span className="text-lg">🧠</span>,
  ShieldAlt: () => <span className="text-lg">🛡️</span>,
  ChartBar: () => <span className="text-lg">📊</span>,
  Mail: () => <span className="text-lg">✉️</span>,
  Phone: () => <span className="text-lg">📞</span>,
  MapPin: () => <span className="text-lg">📍</span>,
}
